// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * rotate_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Particle1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Particle2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Particle3_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Wave1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Wave2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * appear_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * disappear_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * odsouiahda_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * YoloPonit1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * YoloPoint2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * YoloPoint3_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * DynamicIsland_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * coinlocked_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * coinunlocked_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * YoloPoint0_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fanbar_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fanbardisappear_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * rotateback_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_877801452);    // assets/4G信号.png
LV_IMG_DECLARE(ui_img_wifi1_png);    // assets/WIFI1.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/WIFI.png
LV_IMG_DECLARE(ui_img_1152878764);    // assets/电池电量.png
LV_IMG_DECLARE(ui_img_uncharge_png);    // assets/uncharge.png
LV_IMG_DECLARE(ui_img_charge_green_png);    // assets/charge green.png
LV_IMG_DECLARE(ui_img_lightning_png);    // assets/lightning.png
LV_IMG_DECLARE(ui_img_1269858994);    // assets/身份识别.png
LV_IMG_DECLARE(ui_img_781516624);    // assets/电子器件mdpi.png
LV_IMG_DECLARE(ui_img_944254084);    // assets/天气.png
LV_IMG_DECLARE(ui_img_1947152321);    // assets/实验室.png
LV_IMG_DECLARE(ui_img_2124969408);    // assets/电源计算工具.png
LV_IMG_DECLARE(ui_img_1741439431);    // assets/信息.png
LV_IMG_DECLARE(ui_img_119155942);    // assets/锁定.png
LV_IMG_DECLARE(ui_img_2147162729);    // assets/解锁.png
LV_IMG_DECLARE(ui_img_pipline_png);    // assets/pipline.png
LV_IMG_DECLARE(ui_img_id_card_png);    // assets/id card.png
LV_IMG_DECLARE(ui_img_8836358);    // assets/3.1-扫码.png
LV_IMG_DECLARE(ui_img_1113134515);    // assets/导出.png
LV_IMG_DECLARE(ui_img_dark_png);    // assets/dark.png
LV_IMG_DECLARE(ui_img_b401_png);    // assets/b401.png
LV_IMG_DECLARE(ui_img_b402_png);    // assets/b402.png
LV_IMG_DECLARE(ui_img_b403_png);    // assets/b403.png
LV_IMG_DECLARE(ui_img_b404_png);    // assets/b404.png
LV_IMG_DECLARE(ui_img_fan_png);    // assets/fan.png
LV_IMG_DECLARE(ui_img_b405_png);    // assets/B405.png
LV_IMG_DECLARE(ui_img_digit_png);    // assets/digit.png
LV_IMG_DECLARE(ui_img_1210169952);    // assets/功率曲线评估.png
LV_IMG_DECLARE(ui_img_1620289977);    // assets/电压.png
LV_IMG_DECLARE(ui_img_1630681091);    // assets/电流.png
LV_IMG_DECLARE(ui_img_1462846121);    // assets/功率.png
LV_IMG_DECLARE(ui_img_1567896638);    // assets/天.png
LV_IMG_DECLARE(ui_img_545021016);    // assets/湿度.png
LV_IMG_DECLARE(ui_img_486395812);    // assets/灯.png
LV_IMG_DECLARE(ui_img_696992780);    // assets/气压.png
LV_IMG_DECLARE(ui_img_pan_png);    // assets/pan.png
LV_IMG_DECLARE(ui_img_gas_png);    // assets/gas.png
LV_IMG_DECLARE(ui_img_cpu_png);    // assets/cpu.png
LV_IMG_DECLARE(ui_img_1636984869);    // assets/开发板.png
LV_IMG_DECLARE(ui_img_610600012);    // assets/ram-line.png
LV_IMG_DECLARE(ui_img_npu_png);    // assets/NPU.png
LV_IMG_DECLARE(ui_img_emmc_png);    // assets/eMMC.png
LV_IMG_DECLARE(ui_img_255534165);    // assets/蜂窝网络@2x.png
LV_IMG_DECLARE(ui_img_1005151649);    // assets/版本.png
LV_IMG_DECLARE(ui_img_2026056291);    // assets/lvgl (2).png
LV_IMG_DECLARE(ui_img_1271700976);    // assets/抢险队伍.png

// FONTS
LV_FONT_DECLARE(ui_font_Fnot9);
LV_FONT_DECLARE(ui_font_Font10);
LV_FONT_DECLARE(ui_font_Font11);
LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_Font13);
LV_FONT_DECLARE(ui_font_Font14);
LV_FONT_DECLARE(ui_font_Font15);
LV_FONT_DECLARE(ui_font_Font16);
LV_FONT_DECLARE(ui_font_Font17);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font3);
LV_FONT_DECLARE(ui_font_Font4);
LV_FONT_DECLARE(ui_font_Font5);
LV_FONT_DECLARE(ui_font_Font6);
LV_FONT_DECLARE(ui_font_Font7);
LV_FONT_DECLARE(ui_font_Font8);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
